global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.Logging;
global using Carter;
global using System.Reflection;
global using FluentValidation;
global using Shared.CQRS;
global using System.Diagnostics;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;

global using Shared.Data.Seed;
global using Shared.DDD;
global using Shared.Behaviors;